### ISSUE TITLE
eBook-speaker 6.2 crashes on Debian 12

### ISSUE THREAD

**Issue by patrick-emmabuntus** [book-readers/ebook-speaker#4]
Hello all,

On Emmabuntüs DE 5 based on Debian 12, when I use the version of eBook-speaker (6.2) planned for this version it crashes with this message:

>
> You need to be a member of the group "audio".
> Please give the following command:
>
>    sudo gpasswd -a <login-name> audio
>
> Logout and login again and you can use daisy-player.

Of course the user is in the audio group, see attached screenshot.

The same problem exists on the eBook-speaker version present on Debian 11, however the eBook-speaker 5.0 version present in Debian 10 does not have this problem see screenshot in attachment.

Do you have any advice to resolve this problem?

Thanks in advance for your help.

![Test_ebook_speaker_6 2](https://github.com/book-readers/ebook-speaker/assets/84545964/c7da77a5-3993-4d01-8aaf-7ba2b319a238)

![Test_ebook_speaker_5 0](https://github.com/book-readers/ebook-speaker/assets/84545964/86bc1a61-0c62-48ad-b759-683a8f2f7599)

**Comment by sthibaul** [comment]
Could you check that the program below shows your id?

[test.c.zip](https://github.com/book-readers/ebook-speaker/files/14233391/test.c.zip)

**Comment by patrick-emmabuntus** [comment]
Thank you @sthibaul  for your help.

After compiling your program with gcc, it returns this see screenshot under Emmabuntüs DE 5 based on Debian 12:

![return_test](https://github.com/book-readers/ebook-speaker/assets/84545964/f6ee20cc-efb0-4da9-9615-471f55ad32f5)

**Comment by sthibaul** [comment]
Mmmm, that's really  odd. Could you try the attached program?
[test.c.zip](https://github.com/book-readers/ebook-speaker/files/14233801/test.c.zip)

**Comment by patrick-emmabuntus** [comment]
Here is the return of the new program:

![return_test2](https://github.com/book-readers/ebook-speaker/assets/84545964/21aeda6d-c1fe-459a-8083-3f448ea83765)

**Comment by sthibaul** [comment]
ouch, that truncation...

**Comment by sthibaul** [comment]
Could you check the attached program?
[test.c.zip](https://github.com/book-readers/ebook-speaker/files/14233950/test.c.zip)

**Comment by patrick-emmabuntus** [comment]
@sthibaul here is the return of the 3rd program:

![return_test3](https://github.com/book-readers/ebook-speaker/assets/84545964/aa92b923-e3f5-4340-b6c1-afaaf108f419)

**Comment by sthibaul** [comment]
ok, good :D

**Comment by patrick-emmabuntus** [comment]
Thank you @sthibaul  for your help and if I understood correctly it is a problem with the length of the user name.

**Comment by sthibaul** [comment]
Yes, that's simply it...

**Comment by sthibaul** [comment]
FI, I have requested a bookworm update to fix this bug.

**Comment by patrick-emmabuntus** [comment]
Thanks @sthibaul for your help.

For your information https://emmabuntus.org/emmabuntus-addressing-accessibility-for-visually-impaired/
