### ISSUE TITLE
How to select audio output in command line

### ISSUE THREAD

**Issue by patrick-emmabuntus** [book-readers/ebook-speaker#5]
Hello,

In the ebook-speaker documentation it is indicated that to select the audio output :

```
-d audio_device:audio_type
 eBook-speaker will play on this sound device of given audio_type. The value must be of the form "audio_device:audio_type". Example: "-d  default:alsa",  "hw:0:alsa"  or  "0:pulseaudio".  This option overrules the value in the ~/.eBook-speaker/* config file. Be sure the user is a member of the group "audio".
```

I tried several variations with pulseaudio and also alsa, see below, and I can't find which command I should send to select the audio card with the command line:

![ebook-speaker_pulseaudio](https://github.com/book-readers/ebook-speaker/assets/84545964/8fe2f341-0f74-4588-bdd4-25dced5eb47a)

![ebook-speaker_pulseaudio_ko](https://github.com/book-readers/ebook-speaker/assets/84545964/cf3ddbf7-17b4-4f61-97a2-75f0f32db43c)

What value should I put in the command line to select for example the output of pulseaudio or alsa ?

Thank you in advance for your advice.

**Comment by patrick-emmabuntus** [comment]
Hello,

What I forgot to say in my previous post is that version 5.0.0-1 for Debian 10 did not require adding this option to select the correct audio device. 

Here I am testing version 6.2.0-5 for Debian 13 following this [patch](https://github.com/book-readers/ebook-speaker/issues/4) to use it in the next Emmabuntrüs DE 5, in order to start from a recent version to make fixes in this one to make it ergonomic for blind people.

**Comment by sthibaul** [comment]
as the manual says, using `-d 0:alsa` or `-d 0:pulseaudio` is the way to go.
But you didn't specify which problem you actually encounter, so I cannot say anything else than "works for me". I'm using for instance

```
ebook-speaker -d 0:pulseaudio becquer_legendes_espagnoles.epub  -t "cat eBook-speaker.txt | pico2wave -w eBook-speaker.wav -l fr-FR"
```

Which just works fine. Also, better avoid using a useless cat:

```
ebook-speaker -d 0:pulseaudio becquer_legendes_espagnoles.epub  -t "pico2wave -w eBook-speaker.wav -l fr-FR < eBook-speaker.txt"
```

**Comment by sthibaul** [comment]
> version 5.0.0-1 for Debian 10 did not require adding this option to select the correct audio device

So perhaps for a start it's a question of just selecting a default audio card?

**Comment by sthibaul** [comment]
> as the manual says, using `-d 0:alsa` or `-d 0:pulseaudio` is the way to go. But you didn't specify which problem you actually encounter, so I cannot say anything else than "works for me". I'm using for instance
> 
> ```
> ebook-speaker -d 0:pulseaudio becquer_legendes_espagnoles.epub  -t "cat eBook-speaker.txt | pico2wave -w eBook-speaker.wav -l fr-FR"
> ```
> 
> Which just works fine. Also, better avoid using a useless cat:
> 
> ```
> ebook-speaker -d 0:pulseaudio becquer_legendes_espagnoles.epub  -t "pico2wave -w eBook-speaker.wav -l fr-FR < eBook-speaker.txt"
> ```

Do you mean that the problem is that, for a completely fresh user, the card is still asked for even if `-d` is passed?

**Comment by sthibaul** [comment]
Hoping that I divined correctly

**Comment by patrick-emmabuntus** [comment]
Hello @sthibaul 

Thanks for your help, but using the same command line as you, it still doesn't work.

Sorry if I wasn't very specific. So here's a little video that shows what's going on : http://share.emmabuntus.org/Accessibility/test_start_ebook_speaker_pulseaudio.mp4

I am sending you the book that I use for this test: http://share.emmabuntus.org/Accessibility/lieues.epub

I used a simple line see below, but the goal is to launch the ebook-speaker file manager to select a book from 1000 epub books.

`ebook-speaker -d 0:pulseaudio lieues.epub -t "pico2wave -w eBook-speaker.wav -l fr-FR < eBook-speaker.txt"`

So what I would like to use is this command line:

`ebook-speaker -d 0:pulseaudio /usr/share/Documentation_emmabuntus/Documents/eBooks/  -t "pico2wave -w eBook-speaker.wav -l fr-FR < eBook-speaker.txt"`

I plan to use ebook-speaker to allow visually impaired children in Togo to have access to cultural books in the public domain. You should know that these children do not have many books and that there are very few people who have access to the Internet.

If you are interested in our project here is the first article in English : https://emmabuntus.org/emmabuntus-addressing-accessibility-for-visually-impaired/

Thank you in advance for your advice.

**Comment by sthibaul** [comment]
> here's a little video that shows what's going on : http://share.emmabuntus.org/Accessibility/test_start_ebook_speaker_pulseaudio.mp4

Ok, so this is indeed about the audio-selection-even-if-I-passed-d, which happens only on first execution of ebook-speaker. The commit I have pushed should be fixing this.

**Comment by patrick-emmabuntus** [comment]
Hello @sthibaul 

Thanks for your help, and it work after compile you fixe.

I made a video again so you can see the use of ebook-speaker that we plan to make: 
http://share.emmabuntus.org/Accessibility/ebook-speaker_utilisation.mp4

If you want to help us it would be good not to display:
- the periods between the chapter titles and the page number
- the version, the name of the author in the top banner
- filter the files jeg, opf, displayed in the file explorer

This could be enabled by adding an option when launching ebook-speaker.

Thank you in advance for your help.

**Comment by patrick-emmabuntus** [comment]
Hello @sthibaul

here are my modified files, see the parts with the word "Patrick" : [ebook-speaker-patch.tar.gz](https://github.com/book-readers/ebook-speaker/files/14965893/ebook-speaker-patch.tar.gz)

I leave you free to improve this by adding an option when launching ebook-speaker to activate or not these functions.

**Comment by sthibaul** [comment]
Could you  please open other issues for these points? So they can be discussed: why you'd like them, how to implement them, possibly improve them.

Also, it'd be useful that you learn how to make pull requests on github, that'll simplify reviewing etc.

**Comment by patrick-emmabuntus** [comment]
Hello @sthibaul

I just made the new ticket.

Please tell me where I can find documentation on pull resquet?

I should be able to do this we used a git for our project and I have never done a pull resquet I just do pulls.

**Comment by sthibaul** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
